version: '3.9'

services:

  proxyserver:
    image: nginx:1.21.6
    container_name: staticsite
    working_dir: /usr/share/nginx/html
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./deployment/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      my-net:
        ipv4_address: 172.30.0.20

networks:
  my-net:
    external: true
    name: my-net
