version: "3.9"

services:

  nodeapi:
    build: .
    image: "nodeapi_image"
    container_name: "nodeapi"
    command: ["node", "app.js"]
    networks:
      my-net:
        ipv4_address: 172.30.0.20

networks:
  my-net:
    external: true
    name: my-net
