version: '3.9'

services:

  db:
    image: mysql:5.7.36
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: nginxindocker_database
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "8086:3306"
    networks:
      my-net:
        ipv4_address: 172.30.0.90

networks:
  my-net:
    external: true
    name: my-net
