version: '3.9'

services:

  proxyserver:
    image: nginx:1.21.4
    container_name: proxyserver
    working_dir: /usr/share/nginx/html
    ports:
      - "80:80"
    volumes:
      - ./deployment/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./deployment/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/usr/share/nginx/html:/usr/share/nginx/html:ro
      - ./deployment/var/log/nginx:/var/log/nginx
    networks:
      test-network:
        ipv4_address: 172.23.17.2

networks:
  cops-net:
    external: true
    name: my-net
