version: '3.9'

services:

  webserver:
    image: nginx:latest
    container_name: web
    working_dir: /usr/share/nginx/html
    ports:
      - "80:80"
    volumes:
      - ./deployment/conf/conf.d:/etc/nginx/conf.d:ro
      - ./deployment/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/conf/nginx_helpers.js:/etc/nginx/nginx_helpers.js:ro
      - ./deployment/sites:/usr/share/nginx/html:ro
      - ./deployment/root/.bashrc:/root/.bashrc:ro
      - ./deployment/logs:/var/log/nginx
    networks:
      test-network:
        ipv4_address: 172.23.17.2

networks:
  cops-net:
    external: true
    name: my-net
