version: '3.9'

services:

  apache:
    image: php:apache
    restart: always
    container_name: apache
    environment:
      WORDPRESS_DB_HOST: 172.30.0.90:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: nginxindocker_database
      WORDPRESS_TABLE_PREFIX: x_
      WORDPRESS_DEBUG: 1
      APACHE_LOG_DIR: /logs
    volumes:
      - ./public_html:/var/www/html
      - ./logs:/logs:rw
      - ./deployment/set_servername.conf:/etc/apache2/conf-enabled/set_servername.conf:ro
    networks:
      my-net:
        ipv4_address: 172.30.0.51

networks:
  my-net:
    external: true
    name: my-net
